"""Scaffold service — creates the directory skeleton for a generated project."""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

from foundry_app import __version__ as _FOUNDRY_VERSION
from foundry_app.core.models import CompositionSpec, StageResult
from foundry_app.io.composition_io import save_composition

logger = logging.getLogger(__name__)

# Standard directory structure for a Claude Code project
_CLAUDE_DIRS = [
    ".claude/agents",
    ".claude/commands",
    ".claude/hooks",
    ".claude/skills",
]

_AI_DIRS = [
    "ai/context",
    "ai/outputs",
    "ai/generated/members",
    "ai/generated/expertise",
    "ai/beans",
    "ai/tasks",
    "ai/team",
]


def _render_readme(spec: CompositionSpec) -> str:
    """Render the starter README.md content for a generated project."""
    description = spec.project.description or (
        f"AI-team-backed project for {spec.project.name}."
    )
    today = date.today().isoformat()
    return (
        f"# {spec.project.name}\n"
        "\n"
        f"{description}\n"
        "\n"
        "## Getting Started\n"
        "\n"
        "This project was generated by [Foundry]"
        "(https://github.com/beekeeper-lab/foundry). "
        "The Claude Code context is configured in `CLAUDE.md`. "
        "Start by reading that file for project orientation and the team roster.\n"
        "\n"
        "## Structure\n"
        "\n"
        "- `.claude/` — Claude Code configuration (agents, commands, skills, hooks)\n"
        "- `ai/` — AI team workspace (backlog, outputs, context, team composition)\n"
        "\n"
        "---\n"
        f"Generated by Foundry v{_FOUNDRY_VERSION} on {today}\n"
    )


def scaffold_project(
    spec: CompositionSpec,
    output_dir: str | Path,
) -> StageResult:
    """Create the directory skeleton for a generated Claude Code project.

    Creates the standard directory tree based on the composition spec:
    - ``.claude/`` subdirectories (agents, commands, hooks, skills)
    - ``ai/`` subdirectories (context, outputs, beans, tasks)
    - Per-persona output directories under ``ai/outputs/``

    Existing directories are silently skipped (overlay-safe).

    Args:
        spec: The composition spec describing the project.
        output_dir: Root directory for the generated project.

    Returns:
        A StageResult listing all directories that were created.
    """
    root = Path(output_dir)
    created: list[str] = []
    warnings: list[str] = []

    # Collect all directories to create
    dirs_to_create: list[Path] = []

    # Project root
    dirs_to_create.append(root)

    # .claude/ directories
    for d in _CLAUDE_DIRS:
        dirs_to_create.append(root / d)

    # ai/ directories
    for d in _AI_DIRS:
        dirs_to_create.append(root / d)

    # Per-persona output directories
    for persona in spec.team.personas:
        dirs_to_create.append(root / "ai" / "outputs" / persona.id)

    # Track which directories already exist so we know what we actually created
    existing = {d for d in dirs_to_create if d.exists()}

    # Create all directories
    for dir_path in dirs_to_create:
        dir_path.mkdir(parents=True, exist_ok=True)
        if dir_path not in existing:
            rel = str(dir_path.relative_to(root))
            if dir_path == root:
                rel = "."
            created.append(rel)
            logger.info("Created directory: %s", dir_path)

    if not spec.team.personas:
        warnings.append("No personas selected — no per-persona output directories created")

    # Emit the source composition snapshot so the generated project is
    # round-trippable and passes `validate-repo`'s structural checks. Only
    # count as "written" when the on-disk content actually changes, so a
    # second scaffold pass over an unchanged spec is a true no-op.
    composition_path = root / "ai" / "team" / "composition.yml"
    previous_composition = (
        composition_path.read_text(encoding="utf-8")
        if composition_path.exists()
        else None
    )
    save_composition(spec, composition_path)
    if previous_composition != composition_path.read_text(encoding="utf-8"):
        created.append(str(composition_path.relative_to(root)))
        logger.info("Wrote composition snapshot: %s", composition_path)

    # Emit a starter README.md at the project root. Overlay-safe: do not
    # overwrite an existing README the user has customized.
    readme_path = root / "README.md"
    if not readme_path.exists():
        readme_path.write_text(_render_readme(spec), encoding="utf-8")
        created.append("README.md")
        logger.info("Wrote starter README: %s", readme_path)

    logger.info(
        "Scaffold complete: %d entries created, %d warnings",
        len(created),
        len(warnings),
    )

    return StageResult(wrote=created, warnings=warnings)
