"""Scaffold service — creates the directory skeleton for a generated project."""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

from foundry_app import __version__ as _FOUNDRY_VERSION
from foundry_app.core.models import CompositionSpec, StageResult
from foundry_app.io.composition_io import save_composition

logger = logging.getLogger(__name__)

# Standard directory structure for a Claude Code project
_CLAUDE_DIRS = [
    ".claude/agents",
    ".claude/commands",
    ".claude/hooks",
    ".claude/skills",
]

_AI_DIRS = [
    "ai/context",
    "ai/outputs",
    "ai/generated/members",
    "ai/generated/expertise",
    "ai/beans",
    "ai/tasks",
    "ai/team",
]


def _render_readme(spec: CompositionSpec) -> str:
    """Render the starter README.md content for a generated project."""
    description = spec.project.description or (
        f"AI-team-backed project for {spec.project.name}."
    )
    today = date.today().isoformat()
    return (
        f"# {spec.project.name}\n"
        "\n"
        f"{description}\n"
        "\n"
        "## Getting Started\n"
        "\n"
        "This project was generated by [Foundry]"
        "(https://github.com/beekeeper-lab/foundry). "
        "The Claude Code context is configured in `CLAUDE.md`. "
        "Start by reading that file for project orientation and the team roster.\n"
        "\n"
        "## Structure\n"
        "\n"
        "- `.claude/` — Claude Code configuration (agents, commands, skills, hooks)\n"
        "- `ai/` — AI team workspace (backlog, outputs, context, team composition)\n"
        "\n"
        "---\n"
        f"Generated by Foundry v{_FOUNDRY_VERSION} on {today}\n"
    )


def _render_project_charter(spec: CompositionSpec) -> str:
    """Render the starter ai/context/project-charter.md content.

    The charter is a TODO-marked one-pager personas read first when opening
    the project. Sections (Purpose, Audience, Success Criteria, Non-Goals,
    Constraints) come from BEAN-252 (ADR-003). Block-quoted prompts under
    each heading guide the human filling in the charter.
    """
    if spec.project.description:
        description_line = f"*{spec.project.description}*"
    else:
        description_line = (
            "*TODO: Add a one-line project description in the composition spec.*"
        )
    today = date.today().isoformat()
    return (
        f"# Project Charter — {spec.project.name}\n"
        "\n"
        "> **Status:** TODO — fill in this charter before the team begins "
        "substantive work.\n"
        "> Personas should read this file first when opening the project.\n"
        "\n"
        f"{description_line}\n"
        "\n"
        "## Purpose\n"
        "\n"
        "> What does this project do, in one paragraph? Lead with the "
        "*outcome* (what changes for the user/business when this exists), "
        "not the implementation. A reader should understand the project's "
        "reason for existing in 30 seconds.\n"
        "\n"
        "`TODO: Replace this paragraph with a one-paragraph statement of "
        "purpose.`\n"
        "\n"
        "## Audience\n"
        "\n"
        "> Who is this for? Name the primary user (role, context, what "
        "they're trying to accomplish) and any secondary stakeholders. If "
        "multiple audiences, distinguish them — different audiences usually "
        "imply different success criteria.\n"
        "\n"
        "`TODO: Describe the primary audience and any secondary "
        "stakeholders.`\n"
        "\n"
        "## Success Criteria\n"
        "\n"
        "> What does \"done\" look like? List 3–5 outcome-shaped criteria "
        "the team can point at to say \"yes, we shipped what we set out to "
        "ship.\" Avoid implementation criteria (e.g., \"uses Postgres\") — "
        "describe the change in the world, not the components used.\n"
        "\n"
        "- [ ] `TODO: Outcome criterion 1`\n"
        "- [ ] `TODO: Outcome criterion 2`\n"
        "- [ ] `TODO: Outcome criterion 3`\n"
        "\n"
        "## Non-Goals\n"
        "\n"
        "> What is this project explicitly *not* doing? Non-goals are as "
        "important as goals — they prevent scope creep and tell the team "
        "where to push back. Include things that a reasonable reader might "
        "assume are in scope but are not.\n"
        "\n"
        "- `TODO: Non-goal 1`\n"
        "- `TODO: Non-goal 2`\n"
        "\n"
        "## Constraints\n"
        "\n"
        "> What boundaries does the project operate within? Include "
        "technical constraints (must run on X, must integrate with Y), "
        "organizational constraints (deadline, budget, team size), and "
        "regulatory/compliance constraints. If the project has no hard "
        "constraints, note that explicitly.\n"
        "\n"
        "- `TODO: Constraint 1`\n"
        "- `TODO: Constraint 2`\n"
        "\n"
        "---\n"
        f"Generated by Foundry v{_FOUNDRY_VERSION} on {today}. "
        "Edit freely — this file is overlay-safe.\n"
    )


def scaffold_project(
    spec: CompositionSpec,
    output_dir: str | Path,
) -> StageResult:
    """Create the directory skeleton for a generated Claude Code project.

    Creates the standard directory tree based on the composition spec:
    - ``.claude/`` subdirectories (agents, commands, hooks, skills)
    - ``ai/`` subdirectories (context, outputs, beans, tasks)
    - Per-persona output directories under ``ai/outputs/``

    Existing directories are silently skipped (overlay-safe).

    Args:
        spec: The composition spec describing the project.
        output_dir: Root directory for the generated project.

    Returns:
        A StageResult listing all directories that were created.
    """
    root = Path(output_dir)
    created: list[str] = []
    warnings: list[str] = []

    # Collect all directories to create
    dirs_to_create: list[Path] = []

    # Project root
    dirs_to_create.append(root)

    # .claude/ directories
    for d in _CLAUDE_DIRS:
        dirs_to_create.append(root / d)

    # ai/ directories
    for d in _AI_DIRS:
        dirs_to_create.append(root / d)

    # Per-persona output directories
    for persona in spec.team.personas:
        dirs_to_create.append(root / "ai" / "outputs" / persona.id)

    # Track which directories already exist so we know what we actually created
    existing = {d for d in dirs_to_create if d.exists()}

    # Create all directories
    for dir_path in dirs_to_create:
        dir_path.mkdir(parents=True, exist_ok=True)
        if dir_path not in existing:
            rel = str(dir_path.relative_to(root))
            if dir_path == root:
                rel = "."
            created.append(rel)
            logger.info("Created directory: %s", dir_path)

    if not spec.team.personas:
        warnings.append("No personas selected — no per-persona output directories created")

    # Emit the source composition snapshot so the generated project is
    # round-trippable and passes `validate-repo`'s structural checks. Only
    # count as "written" when the on-disk content actually changes, so a
    # second scaffold pass over an unchanged spec is a true no-op.
    composition_path = root / "ai" / "team" / "composition.yml"
    previous_composition = (
        composition_path.read_text(encoding="utf-8")
        if composition_path.exists()
        else None
    )
    save_composition(spec, composition_path)
    if previous_composition != composition_path.read_text(encoding="utf-8"):
        created.append(str(composition_path.relative_to(root)))
        logger.info("Wrote composition snapshot: %s", composition_path)

    # Emit a starter README.md at the project root. Overlay-safe: do not
    # overwrite an existing README the user has customized.
    readme_path = root / "README.md"
    if not readme_path.exists():
        readme_path.write_text(_render_readme(spec), encoding="utf-8")
        created.append("README.md")
        logger.info("Wrote starter README: %s", readme_path)

    # Emit a starter project charter under ai/context/. Overlay-safe so a
    # filled-in charter is never clobbered. See ADR-003 / BEAN-252.
    charter_path = root / "ai" / "context" / "project-charter.md"
    if not charter_path.exists():
        charter_path.write_text(_render_project_charter(spec), encoding="utf-8")
        created.append(str(charter_path.relative_to(root)))
        logger.info("Wrote starter project charter: %s", charter_path)

    logger.info(
        "Scaffold complete: %d entries created, %d warnings",
        len(created),
        len(warnings),
    )

    return StageResult(wrote=created, warnings=warnings)
